/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package indi.wangsc.hotline;


import indi.wangsc.paperwork.excel.Excel;
import indi.wangsc.paperwork.excel.ExcelFactory;
import org.junit.Test;

public class AppTest {
    @Test
    public void excel(){
        Excel excel= ExcelFactory.get("D:\\result.xlsx");

    }
    
}
